describe("TestHome", () => {
  it("tests TestHome", () => {
    //cy.viewport(1231, 956);
    cy.visit("http://localhost:3000/");
   // cy.get("div.HomeContainer").click();
    cy.get("button.slick-next").click();
    cy.get("button.slick-next").click();
    cy.get("button.slick-next").click();
    cy.get("button.slick-next").click();
    cy.get("button.slick-next").click();
    cy.get("button.slick-next").click();
    cy.get("button.slick-prev").click();
    cy.get("button.slick-prev").click();
    cy.get("button.slick-prev").click();
    cy.get("button.slick-prev").click();
    cy.get("button.slick-prev").click();
    cy.get("button.slick-prev").click();
    cy.get("button.slick-prev").click();
    cy.get("button.slick-prev").click();
    cy.get("button.slick-prev").click();
    cy.get("div.slick-current button").click();
    cy.get("div:nth-of-type(6) button").click();
    cy.get("div:nth-of-type(6) > div > div").click();
    cy.get("div:nth-of-type(7) p").click();
    cy.get("div:nth-of-type(7) button").click();
    cy.get("div.slick-current button").click();
    cy.get("div.slick-current p").click();
    cy.get("div.NewsBox").click();
   // cy.get("div.HomeContainer div:nth-of-type(4)").click();
    cy.get("div.slick-current > div > div").click();
    cy.get("div:nth-of-type(6) > div > div").click();
    cy.get("button.slick-prev").click();
    cy.get("div:nth-of-type(6) button").click();
    cy.get("div.slick-current button").click();
   // cy.get("div:nth-of-type(5) button").click();
    cy.get("button.slick-prev").click();
    cy.get("div:nth-of-type(8) button").click();
    cy.get("div.slick-current button").click();
    cy.get("div:nth-of-type(6) button").click();
    cy.get("button.slick-prev").click();
    cy.get("div:nth-of-type(7) button").click();
    cy.get("div.slick-current button").click();
   // cy.get("div:nth-of-type(5) button").click();
    cy.get("button.slick-prev").click();
    cy.get("div:nth-of-type(7) button").click();
    cy.get("div:nth-of-type(6) button").click();
  });
});
